{"name": "test_sending_form", "status": "broken", "statusDetails": {"message": "ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение", "trace": "self = <allure_commons._allure.fixture object at 0x000002A503DFDD30>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py:231: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nconftest.py:33: in in_browser\n    browser.quit()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selene\\core\\_browser.py:143: in quit\n    self.driver.quit()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py:224: in quit\n    self.service.stop()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:152: in stop\n    self.send_remote_shutdown_command()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:132: in send_remote_shutdown_command\n    request.urlopen(f\"{self.service_url}/shutdown\")\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\urllib\\request.py:189: in urlopen\n    return opener.open(url, data, timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\urllib\\request.py:489: in open\n    response = self._open(req, data)\n               ^^^^^^^^^^^^^^^^^^^^^\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\urllib\\request.py:506: in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\urllib\\request.py:466: in _call_chain\n    result = func(*args)\n             ^^^^^^^^^^^\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\urllib\\request.py:1348: in http_open\n    return self.do_open(http.client.HTTPConnection, req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\urllib\\request.py:1323: in do_open\n    r = h.getresponse()\n        ^^^^^^^^^^^^^^^\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py:1430: in getresponse\n    response.begin()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py:350: in begin\n    self.headers = self.msg = parse_headers(self.fp)\n                              ^^^^^^^^^^^^^^^^^^^^^^\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py:248: in parse_headers\n    headers = _read_headers(fp)\n              ^^^^^^^^^^^^^^^^^\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py:221: in _read_headers\n    line = fp.readline(_MAXLINE + 1)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <socket.SocketIO object at 0x000002A503E16F80>\nb = <memory at 0x000002A503DE8DC0>\n\n    def readinto(self, b):\n        \"\"\"Read up to len(b) bytes into the writable buffer *b* and return\n        the number of bytes read.  If the socket is non-blocking and no bytes\n        are available, None is returned.\n    \n        If *b* is non-empty, a 0 return value indicates that the connection\n        was shutdown at the other end.\n        \"\"\"\n        self._checkClosed()\n        self._checkReadable()\n        if self._timeout_occurred:\n            raise OSError(\"cannot read from timed out object\")\n        try:\n>           return self._sock.recv_into(b)\n                   ^^^^^^^^^^^^^^^^^^^^^^^\nE           ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\socket.py:719: ConnectionResetError"}, "steps": [{"name": "open registration page", "status": "passed", "start": 1760898090837, "stop": 1760898100196}, {"name": "filling personal information", "status": "passed", "start": 1760898100196, "stop": 1760898100542}, {"name": "filling other info", "status": "passed", "start": 1760898100542, "stop": 1760898100645}, {"name": "filling address information", "status": "passed", "start": 1760898100645, "stop": 1760898100824}, {"name": "sending form", "status": "passed", "start": 1760898100824, "stop": 1760898100867}, {"name": "check if registration form is working", "status": "passed", "start": 1760898100867, "stop": 1760898102993}], "start": 1760898090837, "stop": 1760898102993, "uuid": "9dad4660-b743-436a-894c-71c89ee7200e", "historyId": "95c71a0dc1404c6de57a9faa644c6ac7", "testCaseId": "95c71a0dc1404c6de57a9faa644c6ac7", "fullName": "tests.test.test_registration#test_sending_form", "labels": [{"name": "parentSuite", "value": "tests.test"}, {"name": "suite", "value": "test_registration"}, {"name": "host", "value": "DESKTOP-114R2PQ"}, {"name": "thread", "value": "7080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.test_registration"}], "titlePath": ["tests", "test", "test_registration.py"]}